name: Coverage

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 21
                  cache: "maven"
            - name: Maven test and coverage report
              run: mvn -B test jacoco:report
            - name: Coveralls coverage report publish
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
              run: mvn -B coveralls:report
